export { default as Button } from './Button'
export { default as Header } from './Header'
export {default as HeroSection} from './HeroSection'
export {default as ServicesCards} from './ServicesCards'
export {default as Details} from './Details'
export {default as Reviews} from './Reviews'
export {default as FAQs} from './FAQs'
